name: online_food_order
description: A new Flutter project

# Use 'none' for the 'publish_to' field if you're not publishing the package to a package repository.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'  # Specify the Flutter SDK version range.

dependencies:
  flutter:
    sdk: flutter  # Use the Flutter SDK.

  cupertino_icons: ^1.0.2  # Add the Cupertino Icons package.
  flutter_svg: ^2.0.7  # Add the Flutter SVG package.

dev_dependencies:
  flutter_test:
    sdk: flutter  # Include Flutter testing framework.
  flutter_lints: ^2.0.0  # Add linting for code analysis.

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
